apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: deepsea
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: deepsea
    spec:
      containers:
        - name: deepsea
          image: zulucontainerregistry.azurecr.io/deepsea
          ports:
            - containerPort: 8080